# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'DMK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'UIDropDown'
  
  # Pods for DMK

  target 'DMKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DMKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
